[pytest]
pythonpath = .
addopts = -s -v --strict-markers
testpaths = testcases tests
markers =
    smoke: 冒烟测试用例
    core: 核心链路用例
    regression: 完整回归用例
log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s - %(asctime)s - %(filename)s:%(lineno)d - %(message)s
